name: "Build and test Action"
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Hello World
      run: python hello/world/init.py
