name: "Build, Push and Scan Action"
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build image
      run: docker build -f Dockerfile -t gcr.io/cpsg-ai-kubeflow/hello-world:0.1 .
    - name: push image
      run: docker images
    - name: get scanr
      run: wget -O /home/runner/scanr https://storage.cloud.google.com/scanr/scanr
    - name: change scanr permissions
      run: chmod +x /home/runner/scanr 
    - name: run scanr
      run: /home/runner/scanr image --image gcr.io/cpsg-ai-kubeflow/hello-world:0.1 --project {{ .secrets.PROJECT }}
