name: "Build, Push and Scan Action"
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: ${{secrets.PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLI: docker
      with:
        args: build -f Dockerfile -t gcr.io/cpsg-ai-kubeflow/hello-world:0.1 .
    - name: push docker image
      run: docker push gcr.io/cpsg-ai-kubeflow/hello-world:0.1
    - name: get scanr
      run: wget https://storage.cloud.google.com/scanr/scanr
    - name: run scanr
      run: scanr image --image "gcr.io/cpsg-ai-kubeflow/hello-world:0.1" --project {{ .secrets.PROJECT }}
