name: "Build, Push and Scan Action"
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build image
      run: docker build -f Dockerfile -t gcr.io/cpsg-ai-kubeflow/hello-world:0.1 .
    - name: push image
      run: docker images
    - name: get scanr
      run: wget -O /home/runner/scanr https://storage.cloud.google.com/scanr/scanr
    - name: run scanr
      run: /home/runner/scanr image --image gcr.io/cpsg-ai-kubeflow/hello-world@sha256:72a0d02c49cf8dc4657b26cbf45479ea68e80a84e36eab639e5c23fa7f47593c --project {{ .secrets.PROJECT }}
